### ISSUE TITLE
`spacchetti insdhall` does not work

### ISSUE THREAD

**Issue by entyo** [justinwoo/vidtracker#23]
## Environment

- OS: Ubuntu 18.04.1 LTS
- Shell: zsh

## Output

```
$ nix-shell --run make
npm install
npm WARN vidtracker@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 7959 packages in 3.665s
found 0 vulnerabilities

dhall format --inplace packages.dhall

Error: Invalid input

(stdin):4:1:
  |
4 | let upstream =
  | ^^
unexpected "le"
expecting "!=", "&&", "++", "->", "//", "//\\", "/\", "==", "as", "in", "||", "→", "∧", "⩓", "⫽", '#', '*', '+', ':', '?', or whitespace

make: *** [Makefile:8: purs-deps] Error 1
```

```
$ spacchetti insdhall


Error: Invalid input

(stdin):4:1: error: Invalid
    sha256
    hash, expected: whitespace
let upstream =
^
spacchetti: user error (failed to insdhall: 1)
```

**Comment by justinwoo** [comment]
Caused by old Dhall version, but this doesn't readily make sense to me. What are the versions of `dhall` and `dhall-to-json` in nix-shell?

**Comment by justinwoo** [comment]
Oh this is vidtracker, so maybe the easy-purescript impot is just pointing to an old version. You might see if getting the newest references via `nix-prefetch-github justinwoo easy-purescript-nix` and updating the expression in `default.nix` makes this work correctly

**Comment by entyo** [comment]
It worked! thank you :pray:

**Comment by entyo** [comment]
nix-prefetch-github: https://pypi.org/project/nix-prefetch-github/

**Comment by justinwoo** [comment]
could you PR your update? probably travis in its current state would fail

**Comment by entyo** [comment]
@justinwoo Created #24
